### ISSUE TITLE
Sail won't delete 

### ISSUE THREAD

**Issue by crimsonredwolf** [zolantris/ValheimMods#131] opened 2024-08-29 00:15 UTC
### What happened?

I was using the crafting hammer and making a sail with 3 points - I was testing to see how placing sails worked.   I placed it on the deck of my ship.  But now it won't delete and moves with the ship.  I've tried destroying the pieces around it but it continues to sit in the air.  I can't access it.  Or change the color pattern like I could on another sail.  The sail is there...but not there at the same time.   I was bale to replicate this off the ship.  If it's too small you can't access it to delete it.   I made a larger one (off the ship)  and could access and change and delete it.  

### Steps to reproduce

1.)  Click on 3 sided sail
2.)  Place your 3 sides in 
3.)  make a (small)  sail 

### Log outputs

```txt
[Info   : Unity Log] 08/28/2024 17:00:47: Loading dungeon

[Info   : Unity Log] 08/28/2024 17:00:47: Dungeon loaded with 39 rooms in 1.0448 ms.

[Info   : Unity Log] 08/28/2024 17:00:47: Loading room prefabs asynchronously

[Error  : Unity Log] [Physics.PhysX] QuickHullConvexHullLib::findSimplex: Simplex input points appers to be coplanar.
[Error  : Unity Log] Failed to create Convex Mesh from source mesh "". An internal unspecified error has occured that could mean the Quickhull algorithm found the input mesh topologically challenging.
[Error  : Unity Log] [Physics.PhysX] QuickHullConvexHullLib::findSimplex: Simplex input points appers to be coplanar.
[Error  : Unity Log] Failed to create Convex Mesh from source mesh "". An internal unspecified error has occured that could mean the Quickhull algorithm found the input mesh topologically challenging.
[Error  : Unity Log] [Physics.PhysX] QuickHullConvexHullLib::findSimplex: Simplex input points appers to be coplanar.
[Error  : Unity Log] Failed to create Convex Mesh from source mesh "". An internal unspecified error has occured that could mean the Quickhull algorithm found the input mesh topologically challenging.
[Info   : Unity Log] 08/28/2024 17:00:48: Spawning dungeon

[Info   : Unity Log] 08/28/2024 17:00:51: Spawned after 8.019994

[Info   : Unity Log] 08/28/2024 17:05:24: Placed MBSailCreator_3

[Error  :ValheimRAFT.SailComponent] SailCornersCount: 0 is corrupt or mismatches the last ValheimRAFT version. Destroying this component to prevent errors
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
(wrapper dynamic-method) WearNTear.DMD<WearNTear::Destroy>(WearNTear,HitData)
ValheimRAFT.SailComponent.DestroySelfOnError () (at <8152f05d0780430a8b6ccefb11efb05a>:0)
ValheimRAFT.SailComponent.LoadZDO () (at <8152f05d0780430a8b6ccefb11efb05a>:0)
ValheimRAFT.SailComponent.OnEnable () (at <8152f05d0780430a8b6ccefb11efb05a>:0)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
ValheimRAFT.SailCreatorComponent:CreateSailFromCorners()
ValheimRAFT.SailCreatorComponent:Awake()
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
Player:DMD<Player::PlacePiece>(Player, Piece)
Player:UpdatePlacement(Boolean, Single)
Player:Update()

[Error  : Unity Log] [Physics.PhysX] QuickHullConvexHullLib::findSimplex: Simplex input points appers to be coplanar.
[Error  : Unity Log] Failed to create Convex Mesh from source mesh "". An internal unspecified error has occured that could mean the Quickhull algorithm found the input mesh topologically challenging.
[Info   : Unity Log] 08/28/2024 17:05:25: Placed MBSailCreator_3

[Info   : Unity Log] 08/28/2024 17:06:10: Placed MBSailCreator_3

[Info   : Unity Log] 08/28/2024 17:06:12: Placed MBSailCreator_3

[Error  :ValheimRAFT.SailComponent] SailCornersCount: 0 is corrupt or mismatches the last ValheimRAFT version. Destroying this component to prevent errors
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
(wrapper dynamic-method) WearNTear.DMD<WearNTear::Destroy>(WearNTear,HitData)
ValheimRAFT.SailComponent.DestroySelfOnError () (at <8152f05d0780430a8b6ccefb11efb05a>:0)
ValheimRAFT.SailComponent.LoadZDO () (at <8152f05d0780430a8b6ccefb11efb05a>:0)
ValheimRAFT.SailComponent.OnEnable () (at <8152f05d0780430a8b6ccefb11efb05a>:0)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
ValheimRAFT.SailCreatorComponent:CreateSailFromCorners()
ValheimRAFT.SailCreatorComponent:Awake()
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
Player:DMD<Player::PlacePiece>(Player, Piece)
Player:UpdatePlacement(Boolean, Single)
Player:Update()

[Info   : Unity Log] 08/28/2024 17:06:17: Placed MBSailCreator_3

[Info   :ValheimRAFT.UI.PanelUtil+<>c] PANEL_UTIL CHILD CornerA
[Info   :ValheimRAFT.UI.PanelUtil+<>c] PANEL_UTIL CHILD CornerB
```

### Environment

```markdown
OS:
- **OS**: Windows 11 | Ubuntu 20.04
- **Graphics**: DX11 (or Vulkan)
Mods:
- **BepInEx**: 5.4.2202
- Jotunn 2.15.2
- **ValheimRAFT**: Major.Minor.Patch
```

**Comment by zolantris** [comment] 2024-08-29 02:46
Duplicate of #100 please reference older issues for solutions / workarounds. Tri sails are buggy right now.

**Closed** 2024-12-03 08:04 UTC
Labels: bug
