### ISSUE TITLE
A lot of console error marks

### ISSUE THREAD

**Issue by dominik199818** [zolantris/ValheimMods#38] opened 2023-12-30 12:30 UTC
### What happened?

why the hell u not test this modpack when update...

### Steps to reproduce

in game

### Environment

```markdown
OS:
- **OS**: Windows 11 | Ubuntu 20.04
- **Graphics**: DX11 (or Vulkan)
Mods:
- **BepInEx**: 5.4.2202
- Jotunn 2.15.2
- **ValheimRAFT**: 1.7.0
```

**Comment by zolantris** [comment] 2023-12-30 19:44
Please be respectful. You as the user choose to use a mod. Not all updates are guaranteed stable for all user use cases, nor do/will all edge cases get tested. 

Also for future posts, please attach logs, otherwise I cannot help you or figure out why there is an issue.

In this case, planbuild was the culprit and also any mod that manually patched methods within this mod. I made sure to fix this, but in doing so, it means ValheimRAFT may not function as intended especially if the those mods patch older features of valheim raft.

This issue should be fixed in release 1.6.9

**Closed by zolantris** 2023-12-30 19:44 UTC
Labels: bug
